import { AdminLayout } from '../components/AdminLayout'
import { PageHead } from '../components/ui'
import { tokens as t } from '../lib/tokens'

const clauses: { h: string; b: string }[] = [
  {
    h: '1. Role of Ronin — facilitation only',
    b: 'Ronin POS provides software that facilitates communication, record-keeping, and payment coordination between festival organizers, vendors, and their representatives. Ronin is not a party to any merchandise, consignment, or settlement agreement between those parties. All commercial terms — splits, fees, deal points, and payment obligations — are agreed directly between the organizer and the vendor (or the vendor’s representative).',
  },
  {
    h: '2. Settlement statements',
    b: 'Settlement statements generated by Ronin reflect figures entered or captured by the parties. In the absence of a formal invoice, a settlement statement serves as the parties’ shared record of monies due in connection with merchandise gross sales. Ronin does not independently verify counts, rates, or figures and is not liable for amounts that are disputed between the parties.',
  },
  {
    h: '3. Payments',
    b: 'Where payouts are processed through Ronin’s payment partners, Ronin transmits funds according to instructions confirmed by the organizer. Ronin does not hold, own, or guarantee vendor funds and is not responsible for delays or failures originating with a third-party bank, card network, or payment processor.',
  },
  {
    h: '4. Data & access',
    b: 'Access to data is governed by the permission tiers configured for the event (Organizer, Vendor Manager, Vendor). Each party is responsible for the accuracy of the data it enters and for maintaining the confidentiality of its credentials.',
  },
  {
    h: '5. Disputes',
    b: 'Any dispute regarding counts, damages, variances, fees, or amounts due is to be resolved directly between the organizer and the vendor. Ronin’s reconciliation tools are provided to help the parties record and resolve such items; the resolution recorded by the parties governs.',
  },
]

export default function Terms() {
  return (
    <AdminLayout active="Terms">
      <main style={{ padding: '20px 24px 40px', maxWidth: 780 }}>
        <PageHead
          title="Terms &amp; Conditions"
          subtitle="Draft language — Ronin facilitates communication; agreements are between third parties."
        />
        <div style={{ background: t.cardBg, border: `1px solid ${t.cardBorder}`, borderRadius: 8, padding: '8px 26px 20px' }}>
          {clauses.map((c) => (
            <div key={c.h} style={{ padding: '16px 0', borderBottom: `1px solid ${t.divider3}` }}>
              <div style={{ fontSize: 13.5, fontWeight: 700, color: t.heading, marginBottom: 6 }}>{c.h}</div>
              <p style={{ margin: 0, fontSize: 12.5, color: t.secondary, lineHeight: 1.65 }}>{c.b}</p>
            </div>
          ))}
          <p style={{ fontSize: 11, color: t.muted2, marginTop: 16, lineHeight: 1.6 }}>
            Draft for review — not legal advice. Final terms to be prepared with counsel before the October event.
          </p>
        </div>
      </main>
    </AdminLayout>
  )
}
